### ISSUE TITLE
Trying to write Chapters crashes write thread

### ISSUE THREAD

**Issue by bweav19** [jimevans/knuckleball#2]
I found this issue trying to write chapters.

At line 323 of ChapterList.cs 

```
string trackType = NativeMethods.MP4GetTrackType(fileHandle, currentTrackId);

Causes 

System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=mscorlib
  StackTrace:
       at Microsoft.Win32.Win32Native.CoTaskMemFree(IntPtr ptr)
       at Knuckleball.NativeMethods.MP4GetTrackType(IntPtr hFile, Int32 trackId)
       at Knuckleball.ChapterList.WriteToFile(IntPtr fileHandle)
       at Knuckleball.MP4File.Save()
  ....
  InnerException: 
```

Try, catch doesn't work, not sure what else to do with it. 

Thought I would see if you have seen this problem? 

Doesn't really seem to be your code but thought you might have some ideas to handle it gracefully right now it causes a crash and corrupts the mp4 file.

**Comment by JeremyThomas** [comment]
Workaround is to not call MP4GetTrackType.
e.g. modify block at line 319 in ChapterList.cs to be
```csharp
               var referenceTrackId = NativeMethods.MP4FindTrackId(fileHandle, 0, NativeMethods.MP4VideoTrackType, 0);
                if (referenceTrackId == NativeMethods.MP4InvalidTrackId)
                {
                  referenceTrackId = NativeMethods.MP4FindTrackId(fileHandle, 0, NativeMethods.MP4AudioTrackType, 0);
                  if (referenceTrackId == NativeMethods.MP4InvalidTrackId)
                    throw new Exception("No tracks found");
                }
```
